# Font
font_family      JetBrains Nerd Font Mono Regular
font_size        14.0

# Cursor
cursor_shape             block
cursor_blink_interval    0.5
cursor_stop_blinking_after 0

# Window
background_opacity 0.8
background_blur    32

confirm_os_window_close 0

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

paste_actions replace-dangerous-control-codes

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
